version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./:/var/www/html"
        ports:
            - "8000:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: detik
        restart: always
        volumes:
            - "./:/var/www/html"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:latest
        container_name: ${DB_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_USER}
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"